<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bublechat</name>
   <tag></tag>
   <elementGuidId>3a980a67-c331-419d-b52f-27424ca5aab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sc-jtQUzJ.kKquEW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ted-embed-div']/div/div/div/div/div/div/div/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a230100-d2be-4799-85f5-472b79562ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://telkomsel.com/enterprise/ava/platform/revamp/chat.svg</value>
      <webElementGuid>01d20a3d-1559-4e3f-82fe-78f54221b5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jtQUzJ kKquEW</value>
      <webElementGuid>3a99018e-2f39-4189-a46a-0bf28d4277a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ted-embed-div&quot;)/div[@class=&quot;sc-eOzmre whnjM&quot;]/div[@class=&quot;sc-ovuCP cMZQzS&quot;]/div[@class=&quot;sc-eauhAA gtWllA&quot;]/div[@class=&quot;sc-khLCKb fGgvfS&quot;]/div[1]/div[@class=&quot;sc-dstKZu iGxBmS&quot;]/div[@class=&quot;sc-keTIit cxtnCX&quot;]/div[@class=&quot;sc-dpBQxM jeZTrO&quot;]/img[@class=&quot;sc-jtQUzJ kKquEW&quot;]</value>
      <webElementGuid>2362318c-adf8-4eaa-b81c-617dd1752fb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ted-embed-div']/div/div/div/div/div/div/div/div/img[2]</value>
      <webElementGuid>e7d1f1e7-596c-4976-b338-f4454dd48772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://telkomsel.com/enterprise/ava/platform/revamp/chat.svg')]</value>
      <webElementGuid>1356f4f0-28ff-4691-b5c3-dfd006af057b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/img[2]</value>
      <webElementGuid>8fbe861a-196f-493a-abf9-ae0710c249b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://telkomsel.com/enterprise/ava/platform/revamp/chat.svg']</value>
      <webElementGuid>be2a3e47-4cc7-42c6-9b15-b70f712c9a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
