<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mulai Chat</name>
   <tag></tag>
   <elementGuidId>94a2c547-22b0-4cc9-bdee-e6c045473db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.bg-white.text-red-400.mt-2.py-2.text-sm.w-full.rounded-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51d53338-5d8f-4404-815b-62db02f63bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0f0ded23-ea52-4597-b140-0a67e85dbe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white text-red-400 mt-2 py-2 text-sm w-full rounded-full</value>
      <webElementGuid>694e7808-55e4-4525-a22d-b9098110acfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai Chat</value>
      <webElementGuid>7083eb85-3c93-475c-a4cc-4141bbea75fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_77667f __variable_df8903 subpixel-antialiased bg-gray-50&quot;]/div[@class=&quot;h-screen w-full flex&quot;]/div[@class=&quot;h-full w-full flex&quot;]/div[@class=&quot;h-full bg-primary-ted w-full relative overflow-hidden&quot;]/div[@class=&quot;relative h-full flex flex-col justify-between&quot;]/div[@class=&quot;py-4 w-full bg-primary-ted/60 z-50 relative px-3 backdrop-blur-md backdrop-filter flex flex-col flex-grow justify-around&quot;]/div[@class=&quot;px-2&quot;]/form[@class=&quot;space-y-3&quot;]/div[4]/button[@class=&quot;bg-white text-red-400 mt-2 py-2 text-sm w-full rounded-full&quot;]</value>
      <webElementGuid>022c35d6-53d5-41ca-8a76-a15c029b90db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Homepage  Enterprise/iframe_HUBUNGI KAMI_ted-iframe</value>
      <webElementGuid>a2bcee1b-afba-4fbc-9096-cd6aeba698b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2e17e929-8d7c-4f2c-a92e-2f21cb824fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[1]</value>
      <webElementGuid>5f95239f-212e-4ab7-8cf4-4b8e5a08cc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/following::button[1]</value>
      <webElementGuid>09b3290e-06f5-4a30-b869-dc08e5465e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mulai Chat']/parent::*</value>
      <webElementGuid>ff339863-f591-4cdf-9006-5b12d28f2ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>faebcb20-799e-4eb2-84d9-7aa0f7bf7eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Mulai Chat' or . = 'Mulai Chat')]</value>
      <webElementGuid>2033a2d8-0b30-411c-87b3-37b6f94a851e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
