<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chechkbox-input</name>
   <tag></tag>
   <elementGuidId>50e01763-9a6a-40f4-afaf-67833e30f6cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-checkbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54c58a41-0d50-41fa-9c61-592d62d36852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
      <webElementGuid>5658b172-9190-49cc-a096-6d42212b4288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>31abc5de-8c23-4cfe-a368-133cdc11bd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_77667f __variable_df8903 subpixel-antialiased bg-gray-50&quot;]/div[@class=&quot;h-screen w-full flex&quot;]/div[@class=&quot;h-full w-full flex&quot;]/div[@class=&quot;h-full bg-primary-ted w-full relative overflow-hidden&quot;]/div[@class=&quot;relative h-full flex flex-col justify-between&quot;]/div[@class=&quot;py-4 w-full bg-primary-ted/60 z-50 relative px-3 backdrop-blur-md backdrop-filter flex flex-col flex-grow justify-around&quot;]/div[@class=&quot;px-2&quot;]/form[@class=&quot;space-y-3&quot;]/div[@class=&quot;flex space-x-2 items-start&quot;]/label[@class=&quot;ant-checkbox-wrapper css-jxlime&quot;]/span[@class=&quot;ant-checkbox ant-wave-target css-jxlime&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
      <webElementGuid>5111b5a5-fde9-4087-84ee-611cde75d489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Homepage  Enterprise/iframe_HUBUNGI KAMI_ted-iframe</value>
      <webElementGuid>7d8c5f2a-6708-416c-b008-d6e73abfd1be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>7fbdb1ac-1345-4fa0-8de9-6a471de222b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>a4887991-52ed-44c9-8f7a-08f70c7122bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>5ebc2589-5c26-469f-bfe3-b13f6cee0e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
