<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_HUBUNGI KAMI_ted-iframe</name>
   <tag></tag>
   <elementGuidId>d33134a2-5cd9-4564-8062-05f716f69a47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ted-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ted-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d0f5f30f-f1b0-4a47-b3cd-7ac106decc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>fullscreen; microphone</value>
      <webElementGuid>41ae5bf7-2b45-4639-8ed6-250693c96707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>dify chatbot bubble window</value>
      <webElementGuid>f04e2bff-2efc-46b9-a1fd-867072e75231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ted-iframe</value>
      <webElementGuid>c6b148fd-d79f-4909-93b4-842eb69f0608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://telkomsel.com/enterprise/ava/platform/ted?token=0s7TqEwz8f9hl6eV&amp;width=1536&amp;query=</value>
      <webElementGuid>d47fb428-7ac5-4c8a-93d5-990b76c10150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ted-iframe&quot;)</value>
      <webElementGuid>ced8fa31-11dc-4d0d-bbb8-fd2371622e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ted-iframe']</value>
      <webElementGuid>3e16b679-894a-4cd5-8180-b9e287c40350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ted-embed-div']/div/div/div/iframe</value>
      <webElementGuid>9d32cd16-d0e3-429f-bfe9-66adf38c2359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/iframe</value>
      <webElementGuid>7b19662d-639c-458a-a30d-234986cb6c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'dify chatbot bubble window' and @id = 'ted-iframe' and @src = 'https://telkomsel.com/enterprise/ava/platform/ted?token=0s7TqEwz8f9hl6eV&amp;width=1536&amp;query=']</value>
      <webElementGuid>0302900f-eafc-42fb-814f-6ad55c54337f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
